apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
  namespace: project-2
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: django-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target: 
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target: 
        type: Utilization
        averageUtilization: 80
